pipeline { 

	
	agent any
	def app
	stages {
		stage("Checkout") {
			steps { 
				checkout scm
			}
		}

		stage("Build docker image"){
			steps { 
			
   			app = docker.build("python3")		
				
			}
			
		}

	}

}
